# Site settings 配置站点
title: Elvison
subtitle: IOS开发、Nodejs开发
description: ~你的认知束缚你的行动~
keyword: 'Elvison, Elvison的独立博客, 前端, ios, ios开发, IOS博客, javascript, nodejs'
url: 'http://elvison.club' # your host
# if you don't need baseurl, you should leave this value blank.
baseurl: null

permalink: '/:year/:month/:title/'
textColor: null
cover_color: clear

# Author 配置博主信息
avatarTitle: 无所畏惧
avatarDesc: 继续前行

# Comments & social
comment:
  disqus: Elvison
social:
  weibo: '2116897990'
  github: bosong
  mail: songbo469621765@163.com

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Navigation links
blog_button:
  title: 博客主页
nav:
  - title: 所有文章
    description: archive
    url: /archive
  - title: 标签
    description: tags
    url: /tags
  - title: 关于我
    description: about
    url: /about

# Site Admin
jekyll_admin:
  hidden_links: 
    #- posts
    #- pages
    #- staticfiles
    - datafiles
    #- configuration
# Plugins  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

# Build settings
paginate: 20    # pre page count
paginate_path: 'page/:num/'  #分页路径方式
